- name: Hello World Sample
  hosts: all
  vars:
    msg_var: "Hello World!"
    variables: "Hola mundo"
  tasks:
    - name: Add inventory
      ansible.controller.inventory:
        name: "Foo Inventory"
        description: "Our Foo Cloud Servers"
        organization: "Default"
        state: present

