- name: Hello World Sample
  hosts: all
  vars:
    msg_var: "Hello World!"
    variables: "Hola mundo"
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ msg_var  }}"
        
    - name: incluyo variables
      ansible.builtin.include_vars:
        file: vars.yaml
        name: variables
        
    - name: Hello Message 2
      debug:
        msg: "{{ variables  }}"
        
    - name: incluyo variables
      ansible.builtin.include_vars:
        file: vars.yaml
        name: msg_var

    
    - name: Hello Message 3
      debug:
        msg: "{{ msg_var  }}"

