- name: Hello World Sample
  hosts: all
  vars:
    msg_var: "Hello World!"
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ msg_var  }}"
        
    - name: incluyo variables
      ansible.builtin.include_vars:
        file: vars.yaml
        name: msg_var
    - name: Hello Message
      debug:
        msg: "{{ msg_var  }}"

