- name: Lola example
  hosts: all
  vars:
    mensaje_salida: ""
    inven_existe: ""
  tasks:
    - name: Add inventory
      ansible.controller.inventory:
        organization: "Default"
        controller_oauthtoken: "d8kXff3yl8R7qiyp0tfWzpWIUxjaO1"
        controller_host: "192.168.122.69"
        controller_username: "admin"
        controller_password: "password.12"
        name: "Foo Inventory"
        description: "Our Foo Cloud Servers"
        validate_certs: false  
        state: present
      check_mode: true
      register: result_existe

    - name: No existe inventario

      ansible.builtin.set_fact:

        inven_existe: "NO"

        mensaje_salida: "{{ inven_existe }} Error: Inventario no existe."

      when: result_existe is changed

 

    - name: Existe inventario

      ansible.builtin.set_fact:

        inven_existe: "SI"

      when: result_existe is not changed

 

    - name: Resultado de la ejecución existe inventario

      ansible.builtin.debug:

        msg: "{{ mensaje_salida }}"

